go_library(
    name = "mempubsub",
    srcs = ["omem.go"],
    visibility = ["//mettle/..."],
    deps = [
        "///third_party/go/gocloud.dev//gcerrors",
        "///third_party/go/gocloud.dev//pubsub",
        "///third_party/go/gocloud.dev//pubsub/driver",
    ],
)
