version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - copyloopvar
    - gocritic
    - revive
    - misspell
    - prealloc
    - unconvert
    - whitespace
  exclusions:
    paths:
      - plz-out/
      - tests/
    rules:
      - text: SA1019  # Upstream packages seem not to be ready to update protobuf yet
      - text: SA4006  # Too many false positives :(
      - text: SA5008  # Warns for duplicate struct tags which are meaningful to go-flags
      - text: unslice  # This may be useful in some places.
      - text: ifElseChain  # Generally don't agree.
      - text: indent-error-flow # Similar to above, seems to be making questionable choices
      - text: appendAssign
      - text: halp  # Make misspell be quiet about this.
      - text: exitAfterDefer # Potentially useful but not in any cases it fires right now.
      - text: unused-parameter # Quite a few of these, some legit, many are fulfilling interfaces
      - text: redefines-builtin # Not really a big issue
      - text: empty-block # Only came up once and was a false positive. This should be easily handled by review.
      - path: _test\.go
        linters:
          - errcheck
          - dupl

formatters:
  enable:
    - gofmt
  exclusions:
    paths:
      - plz-out/
      - tests/
