run:
  timeout: 5m
  skip-dirs:
    - plz-out/
    - tests/

issues:
  exclude:
    - SA1019  # Upstream packages seem not to be ready to update protobuf yet
    - SA4006  # Too many false positives :(
    - SA5008  # Warns for duplicate struct tags which are meaningful to go-flags
    - unslice  # This may be useful in some places.
    - ifElseChain  # Generally don't agree.
    - indent-error-flow # Similar to above, seems to be making questionable choices
    - appendAssign
    - halp  # Make misspell be quiet about this.
    - exitAfterDefer # Potentially useful but not in any cases it fires right now.
    - unused-parameter # Quite a few of these, some legit, many are fulfilling interfaces
    - redefines-builtin # Not really a big issue
    - empty-block # Only came up once and was a false positive. This should be easily handled by review.
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
linters:
  disable-all: true
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - exportloopref
    - gocritic
    - gofmt
    - revive
    - misspell
    - prealloc
    - unconvert
    - whitespace

    # To consider enabling in future (once we fix errors etc):
    # - maligned
    # - errcheck
    # - scopelint
