go_binary(
    name = "discern",
    srcs = ["main.go"],
    deps = [
        "//cli",
        "//purity/gc",
        "//rexclient",
        "//third_party/go:cli-init",
        "//third_party/go:humanize",
        "//third_party/go:protobuf",
        "//third_party/go:remote-apis",
        "//third_party/go:remote-apis-sdks",
    ],
    visibility = ["//package:all"],
)
