go_binary(
    name = "discern",
    srcs = ["main.go"],
    deps = [
        "//grpcutil",
        "//third_party/go:cli-init",
        "//third_party/go:protobuf",
        "//third_party/go:remote-apis-sdks",
        "//third_party/go:remote-apis",
    ],
)
