go_library(
    name = "common",
    srcs = ["common.go"],
    visibility = ["//mettle/..."],
    deps = [
        "//third_party/go:cli-init",
        "//third_party/go:genproto",
        "//third_party/go/gocloud",
    ],
)
