go_library(
    name = "rexclient",
    srcs = ["client.go"],
    deps = [
        "//grpcutil",
        "//third_party/go:cli-init",
        "//third_party/go:remote-apis",
        "//third_party/go:remote-apis-sdks",
    ],
    visibility = ["PUBLIC"],
)
