plugin_repo(
    name = "go",
    plugin = "go-rules",
    revision = "v1.21.2",
)

plugin_repo(
    name = "cc",
    plugin = "cc-rules",
    revision = "v0.4.0",
)

plugin_repo(
    name = "shell",
    plugin = "shell-rules",
    revision = "v0.2.0",
)

plugin_repo(
    name = "proto",
    plugin = "proto-rules",
    revision = "v0.4.0",
)

plugin_repo(
    name = "go-proto",
    plugin = "go-proto-rules",
    revision = "v0.3.0",
)

plugin_repo(
    name = "python",
    plugin = "python-rules",
    revision = "v1.7.2",
)
