plugin_repo(
    name = "go",
    revision = "bf218045c8e74a03e3821a8c068c9e373980d147",
    owner = "tatskaari",
)

plugin_repo(
    name = "cc",
    revision = "v0.3.1",
)

plugin_repo(
    name = "shell",
    revision = "v0.1.2",
)

plugin_repo(
    name = "proto",
    revision = "v0.2.1",
)

plugin_repo(
    name = "go-proto",
    revision = "v0.2.0",
)

plugin_repo(
    name = "python",
    revision = "v1.2.4",
)
