// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/mettle/mettle.proto

package mettle

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Current       []byte                 `protobuf:"bytes,2,opt,name=Current,proto3" json:"Current,omitempty"`
	LastUpdate    int64                  `protobuf:"varint,5,opt,name=LastUpdate,proto3" json:"LastUpdate,omitempty"`
	SentFirst     bool                   `protobuf:"varint,3,opt,name=SentFirst,proto3" json:"SentFirst,omitempty"`
	Done          bool                   `protobuf:"varint,4,opt,name=Done,proto3" json:"Done,omitempty"`
	StartTime     int64                  `protobuf:"varint,6,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_proto_mettle_mettle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mettle_mettle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_proto_mettle_mettle_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Job) GetCurrent() []byte {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *Job) GetLastUpdate() int64 {
	if x != nil {
		return x.LastUpdate
	}
	return 0
}

func (x *Job) GetSentFirst() bool {
	if x != nil {
		return x.SentFirst
	}
	return false
}

func (x *Job) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *Job) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

type ServeExecutionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServeExecutionsRequest) Reset() {
	*x = ServeExecutionsRequest{}
	mi := &file_proto_mettle_mettle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServeExecutionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServeExecutionsRequest) ProtoMessage() {}

func (x *ServeExecutionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mettle_mettle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServeExecutionsRequest.ProtoReflect.Descriptor instead.
func (*ServeExecutionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_mettle_mettle_proto_rawDescGZIP(), []int{1}
}

type ServeExecutionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServeExecutionsResponse) Reset() {
	*x = ServeExecutionsResponse{}
	mi := &file_proto_mettle_mettle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServeExecutionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServeExecutionsResponse) ProtoMessage() {}

func (x *ServeExecutionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mettle_mettle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServeExecutionsResponse.ProtoReflect.Descriptor instead.
func (*ServeExecutionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_mettle_mettle_proto_rawDescGZIP(), []int{2}
}

func (x *ServeExecutionsResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

var File_proto_mettle_mettle_proto protoreflect.FileDescriptor

const file_proto_mettle_mettle_proto_rawDesc = "" +
	"\n" +
	"\x19proto/mettle/mettle.proto\x12\x1abuild.please.remote.mettle\"\x9f\x01\n" +
	"\x03Job\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x18\n" +
	"\aCurrent\x18\x02 \x01(\fR\aCurrent\x12\x1e\n" +
	"\n" +
	"LastUpdate\x18\x05 \x01(\x03R\n" +
	"LastUpdate\x12\x1c\n" +
	"\tSentFirst\x18\x03 \x01(\bR\tSentFirst\x12\x12\n" +
	"\x04Done\x18\x04 \x01(\bR\x04Done\x12\x1c\n" +
	"\tStartTime\x18\x06 \x01(\x03R\tStartTime\"\x18\n" +
	"\x16ServeExecutionsRequest\"N\n" +
	"\x17ServeExecutionsResponse\x123\n" +
	"\x04jobs\x18\x01 \x03(\v2\x1f.build.please.remote.mettle.JobR\x04jobs2\x87\x01\n" +
	"\tBootstrap\x12z\n" +
	"\x0fServeExecutions\x122.build.please.remote.mettle.ServeExecutionsRequest\x1a3.build.please.remote.mettle.ServeExecutionsResponseB8Z6github.com/thought-machine/please-servers/proto/mettleb\x06proto3"

var (
	file_proto_mettle_mettle_proto_rawDescOnce sync.Once
	file_proto_mettle_mettle_proto_rawDescData []byte
)

func file_proto_mettle_mettle_proto_rawDescGZIP() []byte {
	file_proto_mettle_mettle_proto_rawDescOnce.Do(func() {
		file_proto_mettle_mettle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mettle_mettle_proto_rawDesc), len(file_proto_mettle_mettle_proto_rawDesc)))
	})
	return file_proto_mettle_mettle_proto_rawDescData
}

var file_proto_mettle_mettle_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_mettle_mettle_proto_goTypes = []any{
	(*Job)(nil),                     // 0: build.please.remote.mettle.Job
	(*ServeExecutionsRequest)(nil),  // 1: build.please.remote.mettle.ServeExecutionsRequest
	(*ServeExecutionsResponse)(nil), // 2: build.please.remote.mettle.ServeExecutionsResponse
}
var file_proto_mettle_mettle_proto_depIdxs = []int32{
	0, // 0: build.please.remote.mettle.ServeExecutionsResponse.jobs:type_name -> build.please.remote.mettle.Job
	1, // 1: build.please.remote.mettle.Bootstrap.ServeExecutions:input_type -> build.please.remote.mettle.ServeExecutionsRequest
	2, // 2: build.please.remote.mettle.Bootstrap.ServeExecutions:output_type -> build.please.remote.mettle.ServeExecutionsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_mettle_mettle_proto_init() }
func file_proto_mettle_mettle_proto_init() {
	if File_proto_mettle_mettle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mettle_mettle_proto_rawDesc), len(file_proto_mettle_mettle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mettle_mettle_proto_goTypes,
		DependencyIndexes: file_proto_mettle_mettle_proto_depIdxs,
		MessageInfos:      file_proto_mettle_mettle_proto_msgTypes,
	}.Build()
	File_proto_mettle_mettle_proto = out.File
	file_proto_mettle_mettle_proto_goTypes = nil
	file_proto_mettle_mettle_proto_depIdxs = nil
}
