go_library(
    name = "grpc",
    srcs = glob(["*.go"]),
    deps = [
        "//third_party/go:cli-init",
        "//third_party/go:grpc",
        "//third_party/go:logging",
    ],
    visibility = ["PUBLIC"],
)
