go_library(
    name = "configureablepubsub",
    srcs = ["configureablepubsub.go"],
    visibility = ["//mettle/..."],
    deps = [
        "///third_party/go/gocloud.dev//pubsub",
        "///third_party/go/gocloud.dev//pubsub/gcppubsub",
        "///third_party/go/gocloud.dev//gcp",
    ],
)
