// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/purity/purity.proto

package purity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The prefix of blobs to list. Should be exactly two hex characters.
	Prefix        string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_purity_purity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purity_purity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_purity_purity_proto_rawDescGZIP(), []int{0}
}

func (x *ListRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type ListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of results in the AC on this server.
	ActionResults []*ActionResult `protobuf:"bytes,1,rep,name=action_results,json=actionResults,proto3" json:"action_results,omitempty"`
	// List of blobs this server stores.
	Blobs         []*Blob `protobuf:"bytes,2,rep,name=blobs,proto3" json:"blobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_purity_purity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purity_purity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_purity_purity_proto_rawDescGZIP(), []int{1}
}

func (x *ListResponse) GetActionResults() []*ActionResult {
	if x != nil {
		return x.ActionResults
	}
	return nil
}

func (x *ListResponse) GetBlobs() []*Blob {
	if x != nil {
		return x.Blobs
	}
	return nil
}

// An ActionResult is a reference to an action result with a little additional
// information.
type ActionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	LastAccessed  int64                  `protobuf:"varint,3,opt,name=last_accessed,json=lastAccessed,proto3" json:"last_accessed,omitempty"`
	Replicas      int32                  `protobuf:"varint,4,opt,name=replicas,proto3" json:"replicas,omitempty"`
	CachePrefix   string                 `protobuf:"bytes,5,opt,name=cache_prefix,json=cachePrefix,proto3" json:"cache_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResult) Reset() {
	*x = ActionResult{}
	mi := &file_proto_purity_purity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResult) ProtoMessage() {}

func (x *ActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purity_purity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResult.ProtoReflect.Descriptor instead.
func (*ActionResult) Descriptor() ([]byte, []int) {
	return file_proto_purity_purity_proto_rawDescGZIP(), []int{2}
}

func (x *ActionResult) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ActionResult) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ActionResult) GetLastAccessed() int64 {
	if x != nil {
		return x.LastAccessed
	}
	return 0
}

func (x *ActionResult) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *ActionResult) GetCachePrefix() string {
	if x != nil {
		return x.CachePrefix
	}
	return ""
}

type Blob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Replicas      int32                  `protobuf:"varint,4,opt,name=replicas,proto3" json:"replicas,omitempty"`
	CachePrefix   string                 `protobuf:"bytes,5,opt,name=cache_prefix,json=cachePrefix,proto3" json:"cache_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blob) Reset() {
	*x = Blob{}
	mi := &file_proto_purity_purity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blob) ProtoMessage() {}

func (x *Blob) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purity_purity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blob.ProtoReflect.Descriptor instead.
func (*Blob) Descriptor() ([]byte, []int) {
	return file_proto_purity_purity_proto_rawDescGZIP(), []int{3}
}

func (x *Blob) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Blob) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Blob) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *Blob) GetCachePrefix() string {
	if x != nil {
		return x.CachePrefix
	}
	return ""
}

type DeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Prefix of blobs to delete. Should be exactly two hex characters.
	Prefix string `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// Action results to delete.
	ActionResults []*Blob `protobuf:"bytes,1,rep,name=action_results,json=actionResults,proto3" json:"action_results,omitempty"`
	// CAS blobs to delete.
	Blobs []*Blob `protobuf:"bytes,2,rep,name=blobs,proto3" json:"blobs,omitempty"`
	// True to force a 'hard' delete.
	// False gives the server an option to 'soft' delete them (however it may
	// interpret that).
	Hard          bool `protobuf:"varint,4,opt,name=hard,proto3" json:"hard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_purity_purity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purity_purity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_purity_purity_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *DeleteRequest) GetActionResults() []*Blob {
	if x != nil {
		return x.ActionResults
	}
	return nil
}

func (x *DeleteRequest) GetBlobs() []*Blob {
	if x != nil {
		return x.Blobs
	}
	return nil
}

func (x *DeleteRequest) GetHard() bool {
	if x != nil {
		return x.Hard
	}
	return false
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_purity_purity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purity_purity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_purity_purity_proto_rawDescGZIP(), []int{5}
}

var File_proto_purity_purity_proto protoreflect.FileDescriptor

const file_proto_purity_purity_proto_rawDesc = "" +
	"\n" +
	"\x19proto/purity/purity.proto\x12\x1abuild.please.remote.purity\"%\n" +
	"\vListRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\"\x97\x01\n" +
	"\fListResponse\x12O\n" +
	"\x0eaction_results\x18\x01 \x03(\v2(.build.please.remote.purity.ActionResultR\ractionResults\x126\n" +
	"\x05blobs\x18\x02 \x03(\v2 .build.please.remote.purity.BlobR\x05blobs\"\xa5\x01\n" +
	"\fActionResult\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12#\n" +
	"\rlast_accessed\x18\x03 \x01(\x03R\flastAccessed\x12\x1a\n" +
	"\breplicas\x18\x04 \x01(\x05R\breplicas\x12!\n" +
	"\fcache_prefix\x18\x05 \x01(\tR\vcachePrefix\"x\n" +
	"\x04Blob\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12\x1a\n" +
	"\breplicas\x18\x04 \x01(\x05R\breplicas\x12!\n" +
	"\fcache_prefix\x18\x05 \x01(\tR\vcachePrefix\"\xbc\x01\n" +
	"\rDeleteRequest\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\x12G\n" +
	"\x0eaction_results\x18\x01 \x03(\v2 .build.please.remote.purity.BlobR\ractionResults\x126\n" +
	"\x05blobs\x18\x02 \x03(\v2 .build.please.remote.purity.BlobR\x05blobs\x12\x12\n" +
	"\x04hard\x18\x04 \x01(\bR\x04hard\"\x10\n" +
	"\x0eDeleteResponse2\xc0\x01\n" +
	"\x02GC\x12Y\n" +
	"\x04List\x12'.build.please.remote.purity.ListRequest\x1a(.build.please.remote.purity.ListResponse\x12_\n" +
	"\x06Delete\x12).build.please.remote.purity.DeleteRequest\x1a*.build.please.remote.purity.DeleteResponseB8Z6github.com/thought-machine/please-servers/proto/purityb\x06proto3"

var (
	file_proto_purity_purity_proto_rawDescOnce sync.Once
	file_proto_purity_purity_proto_rawDescData []byte
)

func file_proto_purity_purity_proto_rawDescGZIP() []byte {
	file_proto_purity_purity_proto_rawDescOnce.Do(func() {
		file_proto_purity_purity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_purity_purity_proto_rawDesc), len(file_proto_purity_purity_proto_rawDesc)))
	})
	return file_proto_purity_purity_proto_rawDescData
}

var file_proto_purity_purity_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_purity_purity_proto_goTypes = []any{
	(*ListRequest)(nil),    // 0: build.please.remote.purity.ListRequest
	(*ListResponse)(nil),   // 1: build.please.remote.purity.ListResponse
	(*ActionResult)(nil),   // 2: build.please.remote.purity.ActionResult
	(*Blob)(nil),           // 3: build.please.remote.purity.Blob
	(*DeleteRequest)(nil),  // 4: build.please.remote.purity.DeleteRequest
	(*DeleteResponse)(nil), // 5: build.please.remote.purity.DeleteResponse
}
var file_proto_purity_purity_proto_depIdxs = []int32{
	2, // 0: build.please.remote.purity.ListResponse.action_results:type_name -> build.please.remote.purity.ActionResult
	3, // 1: build.please.remote.purity.ListResponse.blobs:type_name -> build.please.remote.purity.Blob
	3, // 2: build.please.remote.purity.DeleteRequest.action_results:type_name -> build.please.remote.purity.Blob
	3, // 3: build.please.remote.purity.DeleteRequest.blobs:type_name -> build.please.remote.purity.Blob
	0, // 4: build.please.remote.purity.GC.List:input_type -> build.please.remote.purity.ListRequest
	4, // 5: build.please.remote.purity.GC.Delete:input_type -> build.please.remote.purity.DeleteRequest
	1, // 6: build.please.remote.purity.GC.List:output_type -> build.please.remote.purity.ListResponse
	5, // 7: build.please.remote.purity.GC.Delete:output_type -> build.please.remote.purity.DeleteResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_purity_purity_proto_init() }
func file_proto_purity_purity_proto_init() {
	if File_proto_purity_purity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_purity_purity_proto_rawDesc), len(file_proto_purity_purity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_purity_purity_proto_goTypes,
		DependencyIndexes: file_proto_purity_purity_proto_depIdxs,
		MessageInfos:      file_proto_purity_purity_proto_msgTypes,
	}.Build()
	File_proto_purity_purity_proto = out.File
	file_proto_purity_purity_proto_goTypes = nil
	file_proto_purity_purity_proto_depIdxs = nil
}
