go_library(
    name = "gcppubsub",
    srcs = ["gcppubsub.go"],
    visibility = ["//mettle/..."],
    deps = [
        "//third_party/go:api",
        "//third_party/go:cloud_pubsub",
        "//third_party/go:genproto",
        "//third_party/go:google-cloud-go",
        "//third_party/go:grpc",
        "//third_party/go:oauth2",
        "//third_party/go/gocloud",
        "//third_party/go/gocloud:wire",
    ],
)
