go_library(
    name = "rpc",
    srcs = ["rpc.go"],
    deps = [
        "//creds",
        "//proto:record",
        "//sanguine/trie",
        "//third_party/go:bytestream",
        "//third_party/go:cli-init",
        "//third_party/go:errgroup",
        "//third_party/go:grpc",
        "//third_party/go:grpc-middleware",
        "//third_party/go:protobuf",
        "//third_party/go:remote-apis",
    ],
    visibility = ["//sanguine/..."],
)
