python_binary(
    name = "gen_release",
    main = "gen_release.py",
    resources = ["//:version"],
    deps = [
        "//third_party/python:absl",
        "//third_party/python:colorlog",
        "//third_party/python:requests",
    ],
)
