name: Please Servers
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: thoughtmachine/please-servers:20230319
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: plz-out/gen/third_party/go
          key: ${{ runner.os }}-go-${{ hashFiles('third_party/go/BUILD', 'scripts/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run tests
        run: ./pleasew test --profile ci -p -v 2 --exclude //tests/...
      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            plz-out/log
  release:
    needs: [test]
    runs-on: ubuntu-latest
    container:
      image: thoughtmachine/please-servers:20220816
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: plz-out/gen/third_party/go
          key: ${{ runner.os }}-go-${{ hashFiles('third_party/go/BUILD', 'scripts/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build
        run: ./pleasew build --profile ci -p -v notice //package:release_files
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: thought-machine/release-action@master
        with:
          version-file: VERSION
          change-log-file: ChangeLog
          release-files: plz-out/gen/package
