// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/lucidity/lucidity.proto

package lucidity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Worker struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of this worker.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The host name of the machine the worker is on
	Hostname string `protobuf:"bytes,13,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// The version this worker is currently at
	Version string `protobuf:"bytes,12,opt,name=version,proto3" json:"version,omitempty"`
	// The time the worker started at (as a Unix timestamp)
	StartTime int64 `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// The time the server is reporting in at (the server may overwrite this)
	UpdateTime int64 `protobuf:"varint,3,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// A human-readable string describing the current state of the server.
	Status string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	// Whether the worker currently considers itself healthy.
	Healthy bool `protobuf:"varint,5,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// Whether the worker was busy at the point it sent this request.
	Busy bool `protobuf:"varint,6,opt,name=busy,proto3" json:"busy,omitempty"`
	// Whether the worker is now alive or not (note that it is possible to be
	// alive but unhealthy)
	Alive bool `protobuf:"varint,7,opt,name=alive,proto3" json:"alive,omitempty"`
	// A URL containing the last unit of work the server performed.
	LastTask string `protobuf:"bytes,8,opt,name=last_task,json=lastTask,proto3" json:"last_task,omitempty"`
	// Server-side only; indicates whether this server has been shut down.
	Disabled bool `protobuf:"varint,9,opt,name=disabled,proto3" json:"disabled,omitempty"`
	// ID of the currently executing task, if there is one.
	CurrentTask string `protobuf:"bytes,10,opt,name=current_task,json=currentTask,proto3" json:"current_task,omitempty"`
	// The time the current task was started at.
	TaskStartTime int64 `protobuf:"varint,11,opt,name=task_start_time,json=taskStartTime,proto3" json:"task_start_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Worker) Reset() {
	*x = Worker{}
	mi := &file_proto_lucidity_lucidity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Worker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Worker) ProtoMessage() {}

func (x *Worker) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lucidity_lucidity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Worker.ProtoReflect.Descriptor instead.
func (*Worker) Descriptor() ([]byte, []int) {
	return file_proto_lucidity_lucidity_proto_rawDescGZIP(), []int{0}
}

func (x *Worker) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Worker) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Worker) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Worker) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Worker) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *Worker) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Worker) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *Worker) GetBusy() bool {
	if x != nil {
		return x.Busy
	}
	return false
}

func (x *Worker) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *Worker) GetLastTask() string {
	if x != nil {
		return x.LastTask
	}
	return ""
}

func (x *Worker) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *Worker) GetCurrentTask() string {
	if x != nil {
		return x.CurrentTask
	}
	return ""
}

func (x *Worker) GetTaskStartTime() int64 {
	if x != nil {
		return x.TaskStartTime
	}
	return 0
}

type UpdateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if the receiving server should become unavailable until it receives
	// another response saying it's ok to come back to life again.
	ShouldDisable bool `protobuf:"varint,1,opt,name=should_disable,json=shouldDisable,proto3" json:"should_disable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_proto_lucidity_lucidity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lucidity_lucidity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_lucidity_lucidity_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateResponse) GetShouldDisable() bool {
	if x != nil {
		return x.ShouldDisable
	}
	return false
}

type ListWorkersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The worker name to return
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The hostname to return workers for
	Hostname      string `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkersRequest) Reset() {
	*x = ListWorkersRequest{}
	mi := &file_proto_lucidity_lucidity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkersRequest) ProtoMessage() {}

func (x *ListWorkersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lucidity_lucidity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkersRequest.ProtoReflect.Descriptor instead.
func (*ListWorkersRequest) Descriptor() ([]byte, []int) {
	return file_proto_lucidity_lucidity_proto_rawDescGZIP(), []int{2}
}

func (x *ListWorkersRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListWorkersRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type ListWorkersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of all the currently known workers, optionally filtered on the
	// request.
	Workers       []*Worker `protobuf:"bytes,1,rep,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkersResponse) Reset() {
	*x = ListWorkersResponse{}
	mi := &file_proto_lucidity_lucidity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkersResponse) ProtoMessage() {}

func (x *ListWorkersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lucidity_lucidity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkersResponse.ProtoReflect.Descriptor instead.
func (*ListWorkersResponse) Descriptor() ([]byte, []int) {
	return file_proto_lucidity_lucidity_proto_rawDescGZIP(), []int{3}
}

func (x *ListWorkersResponse) GetWorkers() []*Worker {
	if x != nil {
		return x.Workers
	}
	return nil
}

// This is part of the HTTP API; the request to disable a worker.
type Disable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the worker to disable
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// If true, worker is disabled; if false, it will become enabled.
	Disable       bool `protobuf:"varint,2,opt,name=disable,proto3" json:"disable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disable) Reset() {
	*x = Disable{}
	mi := &file_proto_lucidity_lucidity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disable) ProtoMessage() {}

func (x *Disable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lucidity_lucidity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disable.ProtoReflect.Descriptor instead.
func (*Disable) Descriptor() ([]byte, []int) {
	return file_proto_lucidity_lucidity_proto_rawDescGZIP(), []int{4}
}

func (x *Disable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Disable) GetDisable() bool {
	if x != nil {
		return x.Disable
	}
	return false
}

var File_proto_lucidity_lucidity_proto protoreflect.FileDescriptor

const file_proto_lucidity_lucidity_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/lucidity/lucidity.proto\x12\x1cbuild.please.remote.lucidity\"\xf2\x02\n" +
	"\x06Worker\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bhostname\x18\r \x01(\tR\bhostname\x12\x18\n" +
	"\aversion\x18\f \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x1f\n" +
	"\vupdate_time\x18\x03 \x01(\x03R\n" +
	"updateTime\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\ahealthy\x18\x05 \x01(\bR\ahealthy\x12\x12\n" +
	"\x04busy\x18\x06 \x01(\bR\x04busy\x12\x14\n" +
	"\x05alive\x18\a \x01(\bR\x05alive\x12\x1b\n" +
	"\tlast_task\x18\b \x01(\tR\blastTask\x12\x1a\n" +
	"\bdisabled\x18\t \x01(\bR\bdisabled\x12!\n" +
	"\fcurrent_task\x18\n" +
	" \x01(\tR\vcurrentTask\x12&\n" +
	"\x0ftask_start_time\x18\v \x01(\x03R\rtaskStartTime\"7\n" +
	"\x0eUpdateResponse\x12%\n" +
	"\x0eshould_disable\x18\x01 \x01(\bR\rshouldDisable\"D\n" +
	"\x12ListWorkersRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\"U\n" +
	"\x13ListWorkersResponse\x12>\n" +
	"\aworkers\x18\x01 \x03(\v2$.build.please.remote.lucidity.WorkerR\aworkers\"7\n" +
	"\aDisable\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\adisable\x18\x02 \x01(\bR\adisable2\xdc\x01\n" +
	"\bLucidity\x12\\\n" +
	"\x06Update\x12$.build.please.remote.lucidity.Worker\x1a,.build.please.remote.lucidity.UpdateResponse\x12r\n" +
	"\vListWorkers\x120.build.please.remote.lucidity.ListWorkersRequest\x1a1.build.please.remote.lucidity.ListWorkersResponseB:Z8github.com/thought-machine/please-servers/proto/lucidityb\x06proto3"

var (
	file_proto_lucidity_lucidity_proto_rawDescOnce sync.Once
	file_proto_lucidity_lucidity_proto_rawDescData []byte
)

func file_proto_lucidity_lucidity_proto_rawDescGZIP() []byte {
	file_proto_lucidity_lucidity_proto_rawDescOnce.Do(func() {
		file_proto_lucidity_lucidity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lucidity_lucidity_proto_rawDesc), len(file_proto_lucidity_lucidity_proto_rawDesc)))
	})
	return file_proto_lucidity_lucidity_proto_rawDescData
}

var file_proto_lucidity_lucidity_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_lucidity_lucidity_proto_goTypes = []any{
	(*Worker)(nil),              // 0: build.please.remote.lucidity.Worker
	(*UpdateResponse)(nil),      // 1: build.please.remote.lucidity.UpdateResponse
	(*ListWorkersRequest)(nil),  // 2: build.please.remote.lucidity.ListWorkersRequest
	(*ListWorkersResponse)(nil), // 3: build.please.remote.lucidity.ListWorkersResponse
	(*Disable)(nil),             // 4: build.please.remote.lucidity.Disable
}
var file_proto_lucidity_lucidity_proto_depIdxs = []int32{
	0, // 0: build.please.remote.lucidity.ListWorkersResponse.workers:type_name -> build.please.remote.lucidity.Worker
	0, // 1: build.please.remote.lucidity.Lucidity.Update:input_type -> build.please.remote.lucidity.Worker
	2, // 2: build.please.remote.lucidity.Lucidity.ListWorkers:input_type -> build.please.remote.lucidity.ListWorkersRequest
	1, // 3: build.please.remote.lucidity.Lucidity.Update:output_type -> build.please.remote.lucidity.UpdateResponse
	3, // 4: build.please.remote.lucidity.Lucidity.ListWorkers:output_type -> build.please.remote.lucidity.ListWorkersResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_lucidity_lucidity_proto_init() }
func file_proto_lucidity_lucidity_proto_init() {
	if File_proto_lucidity_lucidity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lucidity_lucidity_proto_rawDesc), len(file_proto_lucidity_lucidity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lucidity_lucidity_proto_goTypes,
		DependencyIndexes: file_proto_lucidity_lucidity_proto_depIdxs,
		MessageInfos:      file_proto_lucidity_lucidity_proto_msgTypes,
	}.Build()
	File_proto_lucidity_lucidity_proto = out.File
	file_proto_lucidity_lucidity_proto_goTypes = nil
	file_proto_lucidity_lucidity_proto_depIdxs = nil
}
